accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include
from .views import (
    register_view,
    logout_view,
    login_view
)

urlpatterns = [
   
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    # Password Reset urls
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/register/password_reset.html',
        email_template_name='accounts/register/password_reset_email.html',
        subject_template_name='accounts/register/password_reset_subject.txt'), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/register/password_reset_done.html'), name='password_reset_done'),
    path('register-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/register/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/register/password_reset_complete.html'), name='password_reset_complete'),
    path('settings/register/', auth_views.PasswordChangeView.as_view(
        template_name='accounts/register/password_change.html'), name='password_change'),
    path('settings/register/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/register/password_change_done.html'), name='password_change_done'),
]

wholesale/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/models.py
from datetime import timedelta
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin, AbstractUser
)
from django.db.models import Q
from django.template.loader import get_template
from django.urls import reverse
from django.utils import timezone
from django.db.models.signals import pre_save, post_save
from django.conf import settings
from . utils import unique_key_generator
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

DEFAULT_ACTIVATION_DAYS = getattr(settings, 'DEFAULT_ACTIVATION_DAYS', 7)


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, first_name=None, last_name=None, contact_number=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            contact_number=contact_number
        )
        user.set_password(password)
        user.is_active = True
        user.save(using=self._db)
        return user

    def create_staff_user(self, email, password, first_name, last_name, contact_number):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
            first_name=first_name,
            last_name=last_name,
            contact_number=contact_number
        )
        user.is_staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, first_name, last_name, contact_number):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
            first_name=first_name,
            last_name=last_name,
            contact_number=contact_number
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name='Email Address', max_length=255, unique=True)
    GENDER = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    ]
    dob = models.DateField(auto_now_add=False, verbose_name='Date of Birth', blank=True, null=True)
    contact_number = models.CharField(max_length=15, verbose_name='Contact Number')
    gender = models.CharField(max_length=1, choices=GENDER, blank=True, null=True)
    is_moderator = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'contact_number']

    objects = UserManager()
    
    def __str__(self):
        return self.email


class EmailActivationQuerySet(models.query.QuerySet):
    def confirmable(self):
        now = timezone.now()
        start_range = now - timedelta(days=DEFAULT_ACTIVATION_DAYS)
        # does my object have a timestamp in here
        end_range = now
        return self.filter(
            activated=False,
            forced_expired=False
        ).filter(
            timestamp__gt=start_range,
            timestamp__lte=end_range
        )


class EmailActivationManager(models.Manager):
    def get_queryset(self):
        return EmailActivationQuerySet(self.model, using=self._db)

    def confirmable(self):
        return self.get_queryset().confirmable()

    def email_exists(self, email):
        return self.get_queryset().filter(
            Q(email=email) |
            Q(user__email=email)
        ).filter(
            activated=False
        )


# class EmailActivation(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     email = models.EmailField()
#     key = models.CharField(max_length=120, blank=True, null=True)
#     activated = models.BooleanField(default=False)
#     forced_expired = models.BooleanField(default=False)
#     expires = models.IntegerField(default=7)  # 7 Days
#     timestamp = models.DateTimeField(auto_now_add=True)
#     update = models.DateTimeField(auto_now=True)
#
#     objects = EmailActivationManager()
#
#     def __str__(self):
#         return self.email
#
#     def can_activate(self):
#         qs = EmailActivation.objects.filter(pk=self.pk).confirmable()  # 1 object
#         if qs.exists():
#             return True
#         return False
#
#     def activate(self):
#         if self.can_activate():
#             # pre activation user signal
#             user = self.user
#             user.is_active = False
#             user.save()
#             # post activation signal for user
#             self.activated = True
#             self.save()
#             return True
#         return False
#
#     def regenerate(self):
#         self.key = None
#         self.save()
#         if self.key is not None:
#             return True
#         return False
#
#     # def send_activation(self):
#     #     if not self.activated and not self.forced_expired:
#     #         if self.key:
#     #             try:
#     #                 base_url = getattr(settings, 'BASE_URL', 'https://belaface.be')
#     #             except:
#     #                 base_url = getattr(settings, 'BASE_URL', 'http://localhost:8000/')
#     #             key_path = reverse("email-activate", kwargs={'key': self.key})  # use reverse
#     #             path = "{base}{path}".format(base=base_url, path=key_path)
#     #             context = {
#     #                 'path': path,
#     #                 'email': self.email,
#     #                 'name': self.user.first_name + ' ' + self.user.last_name
#     #             }
#     #             txt_ = get_template("accounts/email/verify.txt").render(context)
#     #             html_ = get_template("accounts/email/verify.html").render(context)
#     #             subject = '1-Click Email Verification'
#     #             from_email = settings.DEFAULT_FROM_EMAIL
#     #             recipient_list = [self.email]
#     #             sent_mail = send_mail(
#     #                 subject,
#     #                 txt_,
#     #                 from_email,
#     #                 recipient_list,
#     #                 html_message=html_,
#     #                 fail_silently=True,
#     #             )
#     #             return sent_mail
#     #     return False
#
#
# def pre_save_email_activation(sender, instance, *args, **kwargs):
#     if not instance.activated and not instance.forced_expired:
#         if not instance.key:
#             instance.key = unique_key_generator(instance)
#
#
# pre_save.connect(pre_save_email_activation, sender=EmailActivation)
#
#
# def post_save_user_create_receiver(sender, instance, created, *args, **kwargs):
#     if created:
#         obj = EmailActivation.objects.create(user=instance, email=instance.email)
#         obj.send_activation()
#
#
# post_save.connect(post_save_user_create_receiver, sender=User)

#

# @receiver(post_save, sender=User)
# def create_auth_token(sender, instance=None, created=False, **kwargs):
#     if created:
#         Token.objects.create(user=instance)

accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms
from datetime import date

User = get_user_model()


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
    # dob = forms.DateField(input_formats=['%Y-%m-%d'])

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'contact_number',
            ]

    def clean_email(self):
        # print('cleaning mail')
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        # print('cleaning password')
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    # def clean_dob(self):
    #     born = self.cleaned_data.get("dob")
    #     # print(born)
    #     today = date.today()
    #     age = today.year - born.year - ((today.month, today.day) < (born.month, born.day))
    #     # print(age)
    #     if age < 13:
    #         raise forms.ValidationError("You Must be 13!")
    #     return born

    def save(self, commit=True):
        # type: (object) -> object
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get("password"))
        user.is_active = False
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import RegisterForm, LoginForm


def register_view(request):
    if request.method == "POST":
        form = RegisterForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Registration Successfully Completed, Check Your Email To Activate Your Account')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(username=email, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.info(request, f"You are now logged in as {email}")
                return redirect('home')
            else:
                messages.add_message(request, messages.WARNING, "Invalid email or password.")
    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {"form": form})


def logout_view(request):
    messages.add_message(request, messages.WARNING, "You have successfully logged out!")
    logout(request)
    return redirect('home')

accounts/templates/accounts/register/activation_error.html
{% extends "base.html" %}

{% block content %}

    <div class="container-fluid">
        <div class='row'>
            <div class="col col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center py-5">
                {% if key %}
                    <h1 class='my-5 py-5'>Activation Error. Please try again.</h1>
                {% else %}
                    <h1 class='my-5 py-5'>Re-activate your Email Below.</h1>
                {% endif %}
            </div>
            <div class="col-12 text-center">
                <form method='POST' action=''>{% csrf_token %}
                    {{ form.as_p }}
                    <input class='btn btn-default' type='submit' value='Resend Activation' />
                </form>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/register/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Change password || Belaface {% endblock %}

{% block content %}

    <div class="container-fluid">
        <h3 class="text-center font-weight-bold mt-3">Change password</h3>
        <div class="row justify-content-center">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6  mb-5">
                <div class="card" style="background: #F3F3F3">
                    <div class="card-body">
                        <form method="post" novalidate>
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-primary">Change password</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/register/password_change_done.html
{% extends 'root.html' %}

{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}

    <div class="alert alert-success" role="alert">
      <strong>Success!</strong> Your password has been changed!
    </div>
    <a href="{% url 'home' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

accounts/templates/accounts/register/password_reset.html
{% extends 'root.html' %}

{% block title %}Belaface|| Reset Password {% endblock %}

{% block content %}
    <div style="margin: 140px"></div>

    <div class="container-fluid">
        <h2 class="text-center font-weight-bold my-2">
            <a href="{% url 'home' %}" style="text-decoration: none">Belaface</a>
        </h2>
        <div class="row justify-content-center">
            <div class="col-xs-12 col-sm-12 col-lg-5 col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title text-center">Reset your password</h3>
                        <p class="text-justify text-center">Enter your email address and we will send you a link to reset your password.</p>
                        <!---
{#                        <form method="post" novalidate>#}
{#                            {% csrf_token %}#}
{#                            {% include 'includes/form.html' %}#}
{#                            <button type="submit" class="btn btn-primary btn-block">Send register reset email</button>#}
{#                        </form>#}
                        --->
                        <!------ Custom Design -------->
                         <form method="post" novalidate>
                             {% csrf_token %}
                             <div class="form-group">
                                 <input type="email"  name="email" maxlength="254" class="form-control" placeholder="Enter your email address to reset your password" required id="id_email" />
                             </div>
                            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
                        </form>
                        <!---- End Custom Design --->
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/register/password_reset_complete.html
{% extends 'root.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
    <div style="margin: 150px"></div>
    <div class="container">
         <h2 class="text-center font-weight-bold my-4">
            <a href="{% url 'home' %}" style="text-decoration: none">Belaface</a>
        </h2>
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title text-center">Password changed!</h3>
                        <div class="alert alert-success" role="alert">
                            You have successfully changed your password! You may now proceed to log in.
                        </div>
                        <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register/password_reset_confirm.html
{% extends 'root.html' %}

{% block title %}
    {% if validlink %}
        Change password for {{ form.user.username }}
    {% else %}
        Reset your password
    {% endif %}
{% endblock %}

{% block content %}
    <div style="margin-bottom: 120px"></div>
    <div class="container">
        <h2 class="text-center font-weight-bold my-2">
            <a href="{% url 'home' %}" style="text-decoration: none">Belaface</a>
        </h2>
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8 col-sm-10">
                <div class="card">
                    <div class="card-body">
                        {% if validlink %}
                            <h3 class="card-title text-center">Change password for @{{ form.user.username }}</h3>
                            <!---
                            {#<form method="post" novalidate>#}
{#                                {% csrf_token %}#}
{#                                {% include 'includes/form.html' %}#}
{#                                <button type="submit" class="btn btn-success btn-block">Change password</button>#}
{#                            </form>#}
-->
                            <form method="post" novalidate>
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="password" name="new_password1" class="form-control my-2" placeholder="New password" required id="id_new_password1" />
                                    <small class="form-text text-muted">
                                        <ul style="list-style: none">
                                            <li>Your register can&#39;t be too similar to your other personal information.</li>
                                            <li>Your register must contain at least 8 characters.</li>
                                            <li>Your register can&#39;t be a commonly used register.</li>
                                            <li>Your register can&#39;t be entirely numeric.</li>
                                        </ul>
                                    </small>
                                </div>
                                <div class="form-group">
                                    <input type="password" name="new_password2" class="form-control" placeholder="Conform new password" required id="id_new_password2" />
                                </div>
                                <button type="submit" class="btn btn-success btn-block">Change register</button>
                            </form>
                        {% else %}
                            <h3 class="card-title">Reset your password</h3>
                            <div class="alert alert-danger" role="alert">
                                It looks like you clicked on an invalid password reset link. Please try again.
                            </div>
                            <a href="{% url 'password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/register/password_reset_done.html
{% extends 'root.html' %}

{% block title %}Belaface || Reset your password{% endblock %}

{% block content %}
    <div style="margin-bottom: 120px"></div>
    <div class="container">
         <h3 class="text-center font-weight-bold my-3">
             <a href="{% url 'home' %}" style="text-decoration: none">Belaface</a>
         </h3>
        <div class="row justify-content-center">
            <div class="col-xs-12 col-sm-8 col-md-6 col-lg-5 col-xl-5">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title text-center">Reset your password</h3>
                        <p class="text-justify text-center">Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
                        <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/register/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

In case you forgot your username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

If you've received this mail in error, it's likely that another user entered your email address by mistake while trying
to reset a password. If you didn't initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Belaface Limited Team